/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoFoundersRouteImport } from './routes/co-founders'
import { Route as CreateRouteImport } from './routes/create'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as MentorsRouteImport } from './routes/mentors'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as StartupTvRouteImport } from './routes/startup-tv'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as ValidateRouteImport } from './routes/validate'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoFoundersRoute = CoFoundersRouteImport.update({
  id: '/co-founders',
  path: '/co-founders',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsRoute = MentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const StartupTvRoute = StartupTvRouteImport.update({
  id: '/startup-tv',
  path: '/startup-tv',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidateRoute = ValidateRouteImport.update({
  id: '/validate',
  path: '/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/co-founders': typeof CoFoundersRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/mentors': typeof MentorsRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/startup-tv': typeof StartupTvRoute
  '/tools': typeof ToolsRoute
  '/validate': typeof ValidateRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/co-founders': typeof CoFoundersRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/mentors': typeof MentorsRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/startup-tv': typeof StartupTvRoute
  '/tools': typeof ToolsRoute
  '/validate': typeof ValidateRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/co-founders': typeof CoFoundersRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/mentors': typeof MentorsRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/startup-tv': typeof StartupTvRoute
  '/tools': typeof ToolsRoute
  '/validate': typeof ValidateRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/co-founders'
    | '/create'
    | '/dashboard'
    | '/discover'
    | '/mentors'
    | '/profile'
    | '/progress'
    | '/startup-tv'
    | '/tools'
    | '/validate'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/co-founders'
    | '/create'
    | '/dashboard'
    | '/discover'
    | '/mentors'
    | '/profile'
    | '/progress'
    | '/startup-tv'
    | '/tools'
    | '/validate'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/co-founders'
    | '/create'
    | '/dashboard'
    | '/discover'
    | '/mentors'
    | '/profile'
    | '/progress'
    | '/startup-tv'
    | '/tools'
    | '/validate'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoFoundersRoute: typeof CoFoundersRoute
  CreateRoute: typeof CreateRoute
  DashboardRoute: typeof DashboardRoute
  DiscoverRoute: typeof DiscoverRoute
  MentorsRoute: typeof MentorsRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  StartupTvRoute: typeof StartupTvRoute
  ToolsRoute: typeof ToolsRoute
  ValidateRoute: typeof ValidateRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/co-founders': {
      id: '/co-founders'
      path: '/co-founders'
      fullPath: '/co-founders'
      preLoaderRoute: typeof CoFoundersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors': {
      id: '/mentors'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof MentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startup-tv': {
      id: '/startup-tv'
      path: '/startup-tv'
      fullPath: '/startup-tv'
      preLoaderRoute: typeof StartupTvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validate': {
      id: '/validate'
      path: '/validate'
      fullPath: '/validate'
      preLoaderRoute: typeof ValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoFoundersRoute: CoFoundersRoute,
  CreateRoute: CreateRoute,
  DashboardRoute: DashboardRoute,
  DiscoverRoute: DiscoverRoute,
  MentorsRoute: MentorsRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  StartupTvRoute: StartupTvRoute,
  ToolsRoute: ToolsRoute,
  ValidateRoute: ValidateRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
